### ISSUE TITLE
Version 1.x is not compatible with PHP 5.6

### ISSUE THREAD

**Issue by WojtekBrzezinski19** [PrestaShopCorp/module-lib-billing#14]
In version guidance is info that version 1.x is compatible with PHP 5.6:
<img width="846" alt="Zrzut ekranu 2023-01-20 o 11 02 16" src="https://user-images.githubusercontent.com/71131099/213668489-2d04fb6c-2076-4ee4-92f6-7dc8c263f288.png">

But there is a problem, for example:

```php
private function encodeImage(string $image_path)
```
in
https://github.com/PrestaShopCorp/module-lib-billing/blob/1.x/src/Presenter/BillingPresenter.php#L154

I found only this one, but maybe there are more incompatibilities

**Comment by jmcollin** [comment]
Hello @WojtekBrzezinski19!

Thank you for your report

I just made a small PR to fix PHP compatibility
